# Config related
baseURL = "https://essucalgary.netlify.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Engineering Students' Society U of C"

[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Engineering Students Society University of Calgary. All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1

# Nav options
[[menu.footer]]
URL = "about/officehours"
name = "Office Hours"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "resources"
name = "Resources"
parent = "Services"
weight = 1
[[menu.main]]
URL = "projects-Hub"
name = "Projects Hub"
parent = "Get Involved"
weight = 1
[[menu.main]]
URL = "volunteer-Hub"
name = "Volunteer Hub"
parent = "Get Involved"
weight = 2
[[menu.main]]
URL = "get-involved/conferences"
name = "Conferences"
parent = "Get Involved"
weight = 3
[[menu.main]]
URL = "get-involved/applications"
name = "Applications"
parent = "Get Involved"
weight = 4
[[menu.main]]
URL = "get-involved/teams"
name = "Teams"
parent = "Get Involved"
weight = 5
[[menu.main]]
URL = "about/council"
name = "Council"
parent = "About"
weight = 1
[[menu.main]]
URL = "about/departments"
name = "Departments"
parent = "About"
weight = 2
[[menu.main]]
URL = "about/sponsors"
name = "Sponsors"
parent = "About"
weight = 3
[[menu.main]]
URL = "about/constitution"
name = "Constitution"
parent = "About"
weight = 4
[[menu.main]]
URL = "bookings"
name = "Bookings"
parent = "Services"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact us"
weight = 5
[[menu.main]]
hasChildren = true
name = "Get Involved"
weight = 4
[[menu.main]]
hasChildren = true
name = "Services"
weight = 3
[[menu.main]]
URL = "events"
name = "Events"
weight = 2
[[menu.main]]
hasChildren = true
name = "About"
weight = 1


[params]

# Details
author = "Engineering Students' Society University of Calgary"
booking_form_action = "https://formspree.io/mzbjbvzo"
contact_form_action = "#"
custom_css = ["css/custom.css"]
description = "This is meta description"
email = "president@ess.ucalgary.ca"
google_analitycs_id = ""
location = "ENE 134A Engineering Building, University of Calgary 2500 University Drive NW Calgary, AB T2N 1N4"
logo = "images/ess-logo.png"
multi_author = false
phone = "403-220-5737"

# Google maps
[params.gmap]
enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDbEAiNJWJ5U9GWNEbOHJxksvKuz62yehQ&libraries=places"
# map_latitude = "51.080421"
# map_longitude = "-114.132671"
# map_marker = "images/marker.png"
map_photo = "images/contact/ess_map_location.png"
map_link = ""

# Banner
[params.hnotify]
enable = true
link = "/covid-19"
text = "COVID-19 Information"

[params.officehours]
enable = true
link = "/about/officehours"

# Store
[params.nav_button]
enable = true
label = "Store"
link = "https://essstore.square.site/"

# Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""

# Social
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/ess_uofc/"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/company/engineering-students%27-society-u-of-c-/"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/UofC.ESS"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "https://twitter.com/ESS_UofC"